name: Fetch MASP Historical Data

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Find latest MASP epoch and fetch new data
      run: |
        # Find the latest MASP epoch
        LATEST_EPOCH=$(python scripts/find_latest_masp_epoch.py 2>/dev/null | grep "Next MASP epoch to fetch:" | cut -d: -f2 | tr -d ' ')
        
        if [ -z "$LATEST_EPOCH" ]; then
          LATEST_EPOCH=0
        fi
        
        echo "Fetching data starting from MASP epoch: $LATEST_EPOCH"
        python scripts/fetch_data.py --end-masp-epoch $LATEST_EPOCH
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add csv/
        git diff --quiet && git diff --staged --quiet || git commit -m "Update MASP historical data"
        git push 